import { Tour, TransportType } from '../models/tour';

export const MOCK_TOURS: Tour[] = [
  {
    id: 1,
    userId: 2,
    name: 'Wien → Graz',
    description: 'Classic Austrian road trip through Semmering pass',
    from: 'Wien',
    to: 'Graz',
    transportType: TransportType.BIKE,
    distance: 200,
    estimatedTime: 480,
    routeGeoJson: null,
    routeImagePath: '',
    popularity: 3,
    childFriendliness: 2,
    fromCoords: [48.2082, 16.3738],
    toCoords: [47.0707, 15.4395]
  },
  {
    id: 2,
    userId: 2,
    name: 'Innsbruck Trail',
    description: 'Mountain hike through the Nordkette range',
    from: 'Innsbruck Hauptbahnhof',
    to: 'Hafelekar',
    transportType: TransportType.HIKE,
    distance: 12,
    estimatedTime: 240,
    routeGeoJson: null,
    routeImagePath: '',
    popularity: 5,
    childFriendliness: 1,
    fromCoords: [47.2632, 11.3933],
    toCoords: [47.3126, 11.3843]
  },
  {
    id: 3,
    userId: 2,
    name: 'Donaukanal Run',
    description: 'Morning run along the Donaukanal in Vienna',
    from: 'Schwedenplatz',
    to: 'Nussdorf',
    transportType: TransportType.RUNNING,
    distance: 8,
    estimatedTime: 45,
    routeGeoJson: null,
    routeImagePath: '',
    popularity: 7,
    childFriendliness: 4,
    fromCoords: [48.2117, 16.3778],
    toCoords: [48.2553, 16.3575]
  },
  {
    id: 4,
    userId: 2,
    name: 'Salzburg City Walk',
    description: 'Vacation walk through the old town',
    from: 'Mirabell Palace',
    to: 'Festung Hohensalzburg',
    transportType: TransportType.VACATION,
    distance: 3,
    estimatedTime: 60,
    routeGeoJson: null,
    routeImagePath: '',
    popularity: 2,
    childFriendliness: 5,
    fromCoords: [47.8057, 13.0427],
    toCoords: [47.7953, 13.0475]
  }
];
